NumPy enables fast computation in Python, the underlying implementation is in C hence it's blazing fast! The key feature of NumPy is the `ndarray` object. The data type should be homogenous, that is the array should contain elements of single data type.

In [1]:
import numpy as np

vector = np.array([1, 2, 3, 4])
print("Vector: {}".format(vector))
# Every array will have a shape. That is, its dimensions
print("Shape: {}".format(vector.shape))
# Print number of dimensions
print("Dim: {}".format(vector.ndim))
print("Data type: {}".format(vector.dtype))

Vector: [1 2 3 4]
Shape: (4,)
Dim: 1
Data type: int32


The number of dimensions numpy uses is as follows:

`(depth, rows, columns)`

So a 3D array of 3 rows, 2 columns and 2 depth will have following shape:

`(2, 3, 2)`

Which is somewhat counter-intuitive since we expect "2" to be on the other side. This is the convention followed in mostly all libraries. E.g. OpenCV

In [2]:
v = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
v.shape = (2, 3, 2)
print(v)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [3]:
v = np.zeros((2, 3, 2))
print(v)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


## arange
The `arange` function is similar to Python's `range` function. The data type, if not specified, in many cases will be `np.float64`.

In [4]:
a = np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## zeros, zeros_like
`zeros(dim)` will return a np.array of `dim` dimensions initialized with 0. Note that `dim` should be a `tuple`.

`zeros_like(array)` will return a np.array of same dimensions as of `array` initialized with zeros.

#### same functionality with `ones` and `ones_like` except of course the initialization is done with ones.

#### same functionality with `empty` and `empty_like` which will create numpy arrays but won't initialize it with anything (hence, faster) By default, all the values in the array will have garbage values.


In [5]:
print("Zeros")
a = np.zeros((3, 3))
print("A: {}".format(a))
b = np.zeros_like(a)
print("B: {}".format(b))
print("\nOnes")
a = np.ones((3, 3))
print("A: {}".format(a))
b = np.ones_like(a)
print("B: {}".format(b))
print("\nEmpty")
a = np.empty((3, 3))
print("A: {}".format(a))
b = np.empty_like(a)
print("B: {}".format(b))

Zeros
A: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
B: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ones
A: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
B: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Empty
A: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
B: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
